export interface Lesson {
  day: number;
  phase: number;
  phaseName: string;
  title: string;
  scriptureRef: string;
  scriptureText: string;
  lessonText: string;
  memoryHack: string;
  challenge: string;
  prayerStarter: string;
}

export const PHASES: Record<number, { name: string; days: [number, number] }> = {
  1: { name: "Who Is God?", days: [1, 15] },
  2: { name: "The Bible", days: [16, 30] },
  3: { name: "Living It Out", days: [31, 45] },
  4: { name: "Growing Forward", days: [46, 60] },
};

export function getPhaseForDay(day: number): { phase: number; phaseName: string } {
  for (const [phase, info] of Object.entries(PHASES)) {
    const [start, end] = info.days;
    if (day >= start && day <= end) {
      return { phase: Number(phase), phaseName: info.name };
    }
  }
  return { phase: 1, phaseName: "Who Is God?" };
}

export const lessons: Lesson[] = [
  {
    day: 1, phase: 1, phaseName: "Who Is God?", title: "Who is Jesus?",
    scriptureRef: "John 1:1, 14",
    scriptureText: "In the beginning was the Word, and the Word was with God, and the Word was God... And the Word was made flesh, and dwelt among us.",
    lessonText: "Christianity begins here — not with a rule, not with a religion, but with a Person. Jesus is not merely a great teacher or a moral example. He is God himself, clothed in human flesh, walking among us. John opens his Gospel by taking us all the way back to before creation: \"In the beginning was the Word.\" The Word was with God. The Word was God. Then — the miracle — that Word became flesh.\n\nThis is the foundation everything else rests on. If Jesus is who He said He is, then everything changes. If He is God in the flesh, then His words carry absolute authority, His promises are unbreakable, and His sacrifice on the cross is sufficient to pay every debt you have ever owed.",
    memoryHack: "Say \"In the beginning was the Word\" five times while brushing your teeth tonight. Picture the words of John 1:1 written on a blank page — there before anything else existed.",
    challenge: "Write down one thing that surprises you about Jesus being God in human flesh. Don't filter it. Be honest with God about what's hard to believe, and what feels like good news.",
    prayerStarter: "Jesus, I want to know who You really are — not just what I've heard, but the truth. Open my eyes to see You clearly as I begin this journey.",
  },
  {
    day: 2, phase: 1, phaseName: "Who Is God?", title: "God in the Flesh",
    scriptureRef: "Colossians 2:9; Isaiah 9:6",
    scriptureText: "For in him dwelleth all the fulness of the Godhead bodily. — Wonderful, Counsellor, The mighty God, The everlasting Father, The Prince of Peace.",
    lessonText: "Colossians 2:9 is one of the most direct statements in all of Scripture: all the fullness of the Godhead lives in Jesus — bodily. Not symbolically. Not partially. All of it, in a body.\n\nIsaiah, writing 700 years before Jesus was born, described this coming child with an astonishing list of names: Wonderful Counselor. The Mighty God. The Everlasting Father. The Prince of Peace. That is not a description of an angel or a prophet. That is a description of God himself stepping into human history with a name and a face.\n\nYou are not following a philosophy today. You are entering into a relationship with a Person — a Person who is also the Creator of everything that exists.",
    memoryHack: "The names in Isaiah 9:6: Wonderful, Counsellor, Mighty God, Everlasting Father, Prince of Peace. Five names — count them on five fingers.",
    challenge: "Read Isaiah 9:1-7 slowly. Circle every name or description given to Jesus. Then ask yourself: which of these names do I most need Jesus to be in my life right now?",
    prayerStarter: "Lord, You are more than I can fully understand — but I trust that You are exactly who Your Word says You are. Teach me more of You today.",
  },
  {
    day: 3, phase: 1, phaseName: "Who Is God?", title: "Why Do I Need a Savior?",
    scriptureRef: "Romans 3:23; Romans 6:23",
    scriptureText: "For all have sinned, and come short of the glory of God. — For the wages of sin is death; but the gift of God is eternal life through Jesus Christ our Lord.",
    lessonText: "Before you can understand what Jesus did for you, you have to understand why it was necessary. Romans 3:23 does not soften the diagnosis: all have sinned. Not most people. Not the worst people. All. You, me, everyone.\n\nSin is not just a list of bad actions. At its root, sin is living independently from God — making yourself the center of your own universe, deciding for yourself what is right and wrong, owing a debt you cannot repay.\n\nRomans 6:23 is brutally honest about where that leads: the wages of sin is death. But the verse does not stop there. It pivots on the word \"but\": the gift of God is eternal life through Jesus Christ. You cannot earn eternal life. You cannot work your way to it. It is a gift — which means someone else paid the price.",
    memoryHack: "Rom. 3:23 + Rom. 6:23 = the problem and the answer. Problem: all have sinned. Answer: gift of God through Jesus. Say both verses back to back.",
    challenge: "In one honest sentence, describe what \"coming short of the glory of God\" looks like in your own life. This is between you and God.",
    prayerStarter: "God, I admit that I need You. I cannot fix myself or pay my own debt. Thank You that You did not leave us without an answer.",
  },
  {
    day: 4, phase: 1, phaseName: "Who Is God?", title: "What God Did About It",
    scriptureRef: "John 3:16-17; 1 John 4:9-10",
    scriptureText: "For God so loved the world, that he gave his only begotten Son, that whosoever believeth in him should not perish, but have everlasting life.",
    lessonText: "The cross is not a story about God's wrath overcoming His love. It is a story about love so extreme it absorbed wrath entirely. God looked at humanity — broken, rebellious, indebted — and instead of turning away, He came toward us.\n\n1 John 4:10 says this plainly: \"Herein is love, not that we loved God, but that he loved us, and sent his Son to be the propitiation for our sins.\" Propitiation means the complete satisfaction of a debt. Jesus didn't reduce the debt. He paid it in full.\n\nThis is the heart of the Gospel: God loved. God gave. God acted — not because you deserved it, but precisely because you didn't.",
    memoryHack: "John 3:16 — Break it into three parts: God SO loved (motivation) > He GAVE (action) > whosoever believes (your part).",
    challenge: "Sit with John 3:16 for five minutes — not to analyze it, just to receive it. Let the words \"God so loved the world\" include you personally.",
    prayerStarter: "Father, thank You for loving me before I loved You. Help me to truly receive what You gave, not just know about it.",
  },
  {
    day: 5, phase: 1, phaseName: "Who Is God?", title: "What Is Repentance?",
    scriptureRef: "Acts 2:38; Luke 13:3",
    scriptureText: "Then Peter said unto them, Repent, and be baptized every one of you in the name of Jesus Christ for the remission of sins, and ye shall receive the gift of the Holy Ghost.",
    lessonText: "On the Day of Pentecost, when a crowd of thousands heard the Gospel for the first time and asked \"What do we do?\", Peter gave a precise answer: Repent. Be baptized in Jesus' name. Receive the Holy Ghost.\n\nRepentance is the first step, and it is more than regret. The Greek word is metanoia — a change of mind so complete that it changes direction. Picture a U-turn. You were going one way. Repentance turns you completely around.\n\nLuke 13:3 records Jesus saying it plainly: \"except ye repent, ye shall all likewise perish.\" This is not meant to frighten you — it is meant to be honest with you. The door is open, but you have to walk through it. Repentance is how you begin.",
    memoryHack: "Repent = U-turn. Every time you see a U-turn sign this week, say \"Acts 2:38\" out loud.",
    challenge: "Write down three specific areas of your life where you want God to change your direction. Not vague categories — specific things. Then pray over each one.",
    prayerStarter: "Lord, I am turning toward You. I don't want to live on my own terms anymore. Change my direction. I give You these areas of my life today.",
  },
  {
    day: 6, phase: 1, phaseName: "Who Is God?", title: "Repentance Goes Deep",
    scriptureRef: "2 Corinthians 7:10; Acts 3:19",
    scriptureText: "For godly sorrow worketh repentance to salvation not to be repented of: but the sorrow of the world worketh death.",
    lessonText: "There are two kinds of sorrow. Worldly sorrow says: \"I'm sorry I got caught. I'm sorry I feel bad. I'm sorry this is inconvenient.\" Godly sorrow says: \"I'm sorry I sinned against God. I want to be different.\"\n\nOnly one of these leads to genuine change. Worldly sorrow cycles — you feel bad, you feel better, you repeat. Godly sorrow converts. Acts 3:19 uses a beautiful word: your sins may be \"blotted out.\" The original language pictures a wax tablet being wiped completely clean. Nothing left. No trace.\n\nGodly sorrow is not about punishing yourself. It is about taking sin seriously enough to actually let go of it.",
    memoryHack: "Blotted out = completely erased. Picture a whiteboard wiped clean — that is what God does with genuine repentance.",
    challenge: "Ask God to show you the difference between worldly sorrow and godly sorrow in your own life. Where have you been sorry about consequences rather than about the sin itself?",
    prayerStarter: "God, give me genuine repentance — not just sorrow about consequences, but a real desire to be different. Blot out what I bring to You today.",
  },
  {
    day: 7, phase: 1, phaseName: "Who Is God?", title: "Baptism in Jesus' Name",
    scriptureRef: "Acts 2:38; Colossians 2:12",
    scriptureText: "Buried with him in baptism, wherein also ye are risen with him through the faith of the operation of God, who hath raised him from the dead.",
    lessonText: "Baptism in the New Testament is not a symbol that happens after salvation — it is part of the new birth itself. Colossians 2:12 describes it as being buried with Christ and rising with Him. That is not symbolic language for a ceremony. That is language of death and resurrection.\n\nThe consistent pattern in the book of Acts is baptism in the name of Jesus Christ. In Acts 2, 8, 10, and 19, the name used was Jesus. Matthew 28:19 says \"in the name\" (singular) — and Acts shows us what that name is.\n\nBaptism is where repentance meets the water, where the old life is buried and the new life begins. It is not a graduation ceremony — it is a birth.",
    memoryHack: "Buried > Risen. Baptism is a picture of death and resurrection. Jesus died, was buried, rose again — and baptism connects you to that story.",
    challenge: "Read Acts 2:1-41 in one sitting. Mark every action word — what Peter did, what the crowd did, what God did. Notice how baptism fits into the sequence.",
    prayerStarter: "Lord, I want every part of what You offer — repentance, baptism, Your Spirit. Don't let me settle for less than the full new birth.",
  },
  {
    day: 8, phase: 1, phaseName: "Who Is God?", title: "Why the Name of Jesus?",
    scriptureRef: "Acts 4:12; Colossians 2:9",
    scriptureText: "Neither is there salvation in any other: for there is none other name under heaven given among men, whereby we must be saved.",
    lessonText: "Acts 4:12 is one of the most exclusive statements in all of Scripture — and it is not an accident. Peter, standing before the religious authorities who just arrested him, says without flinching: there is no other name. Not \"Jesus is one of many ways.\" There is no other name.\n\nWhen the early church baptized in the name of Jesus, they were applying that singular name to the act of obedience. Colossians 2:9 tells us why: in Jesus dwells all the fullness of the Godhead. \"Father,\" \"Son,\" and \"Holy Ghost\" are titles describing what God is. \"Jesus\" is the name of the One who fills all those titles.\n\nThis is not a technicality. This is the church understanding that there is one God, one name, and one salvation — and it all runs through Jesus.",
    memoryHack: "One name. Write JESUS on a notecard and set it where you'll see it tomorrow morning. Read it aloud when you wake up.",
    challenge: "Ask a believer at your church: \"Why were you baptized in Jesus' name?\" Listen carefully to their answer.",
    prayerStarter: "Jesus — one name, above every name. I declare my trust in Your name alone today.",
  },
  {
    day: 9, phase: 1, phaseName: "Who Is God?", title: "The Holy Spirit — Promise and Person",
    scriptureRef: "Acts 2:1-4; John 7:38-39",
    scriptureText: "And they were all filled with the Holy Ghost, and began to speak with other tongues, as the Spirit gave them utterance.",
    lessonText: "The Holy Spirit is not an atmosphere. The Holy Spirit is not a feeling. The Holy Spirit is not a vague spiritual energy. The Holy Spirit is God — now given to live inside of you.\n\nOn the Day of Pentecost, 120 people in an upper room were filled with the Holy Ghost and spoke in tongues \"as the Spirit gave them utterance.\" This was not emotional overflow. This was a fulfillment of what Jesus promised: \"rivers of living water shall flow out of you.\"\n\nJesus said in Acts 1:8 that you would receive power when the Holy Ghost came upon you. This is not just for apostles. This is not just for the first century. Peter himself said in Acts 2:39: \"the promise is unto you, and to your children, and to all that are afar off.\"",
    memoryHack: "Living water flows — it doesn't sit still. The Holy Spirit in you is active, flowing, alive. Picture a river, not a puddle.",
    challenge: "Spend five extra minutes in prayer tonight after your reading session. Don't rush. Ask God to fill you with His Spirit and then just wait.",
    prayerStarter: "God, I want more of You — not just information about You. Fill me with Your Spirit. Let rivers of living water flow from my life.",
  },
  {
    day: 10, phase: 1, phaseName: "Who Is God?", title: "Speaking in Tongues",
    scriptureRef: "Acts 10:44-46; 1 Corinthians 14:2",
    scriptureText: "For they heard them speak with tongues, and magnify God. — For he that speaketh in an unknown tongue speaketh not unto men, but unto God.",
    lessonText: "When Cornelius's household received the Holy Ghost, the Jewish believers who came with Peter knew it immediately — because they heard them speaking in tongues and magnifying God. The evidence was unmistakable and audible.\n\nSpeaking in tongues is not emotional noise. Paul describes it precisely in 1 Corinthians 14:2: \"he that speaketh in an unknown tongue speaketh not unto men, but unto God.\" Your spirit is communicating with God directly, bypassing the limitations of human language.\n\nThe pattern in Acts is consistent: every time people received the Holy Ghost and the record includes what happened, tongues are present. This is not a denomination's quirk. This is Scripture's record.",
    memoryHack: "Tongues = your spirit talking directly to God. No translator needed between you and Him.",
    challenge: "Read Acts 10:44-48 carefully. Note who received the Holy Ghost and what convinced the eyewitnesses it had happened.",
    prayerStarter: "Father, I don't want to limit You to what I understand. I want to pray in a way that goes deeper than my own words. Fill me and let my spirit speak to You.",
  },
  {
    day: 11, phase: 1, phaseName: "Who Is God?", title: "The New Birth — Putting It Together",
    scriptureRef: "John 3:3-5; Acts 2:38",
    scriptureText: "Jesus answered, Verily, verily, I say unto thee, Except a man be born of water and of the Spirit, he cannot enter into the kingdom of God.",
    lessonText: "Nicodemus was a religious teacher — educated, sincere, respected. And Jesus told him he needed to start over. Be born again. Born of water and of the Spirit.\n\nBorn of water = baptism. Born of the Spirit = Holy Ghost. Acts 2:38 gives the exact prescription: repent (turn), be baptized in Jesus' name (water), receive the Holy Ghost (Spirit). These are not three separate options. They are three parts of one new birth.\n\nRepentance is your yes to God. Baptism is where He buries the old. The Holy Ghost is what He places inside you as He raises the new. The new birth is complete.",
    memoryHack: "Repent + Baptism + Holy Ghost = New Birth. Three movements, one transformation. R-B-H. Say it until it sticks.",
    challenge: "Have you experienced repentance? Have you been baptized in Jesus' name? Have you received the Holy Ghost? Write down honestly where you are and talk to your pastor about next steps.",
    prayerStarter: "Lord Jesus, I want the full new birth — not a portion of it. Do in me everything You want to do. I say yes.",
  },
  {
    day: 12, phase: 1, phaseName: "Who Is God?", title: "What Happens After You're Born Again?",
    scriptureRef: "2 Corinthians 5:17; Ezekiel 36:26",
    scriptureText: "Therefore if any man be in Christ, he is a new creature: old things are passed away; behold, all things are become new.",
    lessonText: "The new birth is not just forgiveness for past sins — it is a new nature. 2 Corinthians 5:17 says \"old things are passed away; behold, all things are become new.\" That word \"behold\" is an invitation to stop and notice. Look at what has changed.\n\nGod promised through Ezekiel: \"A new heart will I give you.\" Not a repaired heart. Not an improved heart. A new one. The problem with the old heart was not bad behavior — it was bad wiring. God does not patch the wiring. He replaces it.\n\nThis does not mean you will never struggle again. But it means your desires begin to shift. What you love starts to change. The Holy Ghost inside you is re-orienting everything from the inside out.",
    memoryHack: "New creature = new species, not a repaired version of the old. You are genuinely different after the new birth.",
    challenge: "Make a simple before/after list: what do you want to be different about yourself after the new birth? Hold onto it — revisit it at Day 30 and Day 60.",
    prayerStarter: "God, make me new. Not improved — new. Change what I love, change what I want, change who I am from the inside out.",
  },
  {
    day: 13, phase: 1, phaseName: "Who Is God?", title: "Assurance — You Can Know",
    scriptureRef: "1 John 5:11-13; Romans 8:16",
    scriptureText: "These things have I written unto you that believe on the name of the Son of God; that ye may know that ye have eternal life.",
    lessonText: "God does not want you living in perpetual uncertainty about your standing with Him. John wrote an entire letter so that believers could know — not hope, not wonder — but know that they have eternal life.\n\nRomans 8:16 describes it beautifully: the Spirit witnesses with your spirit. There is an internal confirmation that God places in those who are His. This is not just a feeling — it is a witness. A testimony.\n\nAssurance is not arrogance. It is not presuming on God's grace. It is simply receiving what God has promised. He is faithful. What He started in you, He intends to complete.",
    memoryHack: "1 John 5:13 — \"that ye may KNOW.\" Circle the word know. God wants you certain, not anxious.",
    challenge: "Write down three specific evidences in your own life that God has been at work in you. Not theological arguments — personal evidence.",
    prayerStarter: "Father, thank You that You want me to know I belong to You. Help me to walk in the confidence of what You have done.",
  },
  {
    day: 14, phase: 1, phaseName: "Who Is God?", title: "The Church — Why It Matters",
    scriptureRef: "Acts 2:42-47; Ephesians 2:19-22",
    scriptureText: "And they continued stedfastly in the apostles' doctrine and fellowship, and in breaking of bread, and in prayers.",
    lessonText: "The new birth does not make you a solo Christian. It makes you part of a family. Acts 2:42-47 shows us what the early church looked like: they gathered consistently, they learned together, they shared meals, they prayed together. The result was that the Lord added to their number daily.\n\nChristianity was never designed to be practiced alone. You need the church. The church needs you. Ephesians 2:19-22 says believers are \"fellow citizens\" and members of God's household — built together into a dwelling place for God.\n\nElkhart Life Church is not just a building you visit on Sundays. It is a community of people on the same journey. They have been where you are. They know the way forward. You belong here.",
    memoryHack: "Four marks of the early church: Doctrine. Fellowship. Bread-breaking. Prayer. Four things — count them on four fingers.",
    challenge: "Commit out loud — to yourself, to God, or to a person you trust — to attend church every Sunday for the remainder of this 60-day journey.",
    prayerStarter: "Lord, thank You that You put me in a family, not just a faith. Help me to show up, to give, and to receive from the people You have placed around me.",
  },
  {
    day: 15, phase: 1, phaseName: "Who Is God?", title: "Phase 1 Review — What You Now Know",
    scriptureRef: "Acts 2:38",
    scriptureText: "Then Peter said unto them, Repent, and be baptized every one of you in the name of Jesus Christ for the remission of sins, and ye shall receive the gift of the Holy Ghost.",
    lessonText: "You have covered the foundation in two weeks. Take inventory of what you now carry.\n\nYou know that Jesus is God in the flesh — the fullness of the Godhead bodily. You know why you need a Savior, and that God provided one freely. You know what repentance means — a real U-turn, not just remorse. You know about baptism in Jesus' name and why the name matters. You know about the Holy Ghost and the evidence of tongues. You know that the new birth is water and Spirit together, and that it produces a genuinely new person.\n\nActs 2:38 is the address of the new birth. Know it by heart. It is the answer Peter gave to a crowd of thousands who asked \"What must we do?\" That answer has not changed.",
    memoryHack: "Acts 2:38 — Repent (your action) + baptized in Jesus' name (water) + receive the Holy Ghost (Spirit) = the full equation. Say it from memory right now.",
    challenge: "Recite Acts 2:38 from memory to someone in your life today. Saying it out loud to another person cements it in a way reading alone cannot.",
    prayerStarter: "God, thank You for these two weeks of foundation. Don't let any of it be just information. Let it be transformation. I am ready for what comes next.",
  },
  {
    day: 16, phase: 2, phaseName: "The Bible", title: "What Is the Bible?",
    scriptureRef: "2 Timothy 3:16-17; Psalm 119:105",
    scriptureText: "All scripture is given by inspiration of God, and is profitable for doctrine, for reproof, for correction, for instruction in righteousness.",
    lessonText: "The Bible is not a collection of ancient wisdom compiled by thoughtful people. It is God-breathed — the Greek word is theopneustos, literally \"blown out by God.\" Forty authors, three continents, fifteen hundred years, one unified message. The statistical improbability of that coherence is itself evidence.\n\nPsalm 119:105 gives a practical picture: a lamp to your feet, a light to your path. A lamp to your feet means enough light for the next step. A light to your path means direction for the long road. The Bible is not a magical book you read once and then know everything. It is a living light you walk in — and the more you walk in it, the more it illuminates.",
    memoryHack: "66 books. Old Testament (39) = Foundation. New Testament (27) = Fulfillment. Together = 66. Think: Route 66 — the road from beginning to destination.",
    challenge: "Start reading one chapter of the Gospel of John each day this week. Just one chapter. Don't study it — just read it like a letter from someone who wants you to know the truth.",
    prayerStarter: "God, Your Word is not just old writing — it is living and active. Help me to read it with expectation, not obligation.",
  },
  {
    day: 17, phase: 2, phaseName: "The Bible", title: "Why Trust the Bible?",
    scriptureRef: "Isaiah 46:9-10; 2 Peter 1:20-21",
    scriptureText: "Holy men of God spake as they were moved by the Holy Ghost.",
    lessonText: "The Bible's credibility is not based on tradition — it is based on evidence. Prophecy is one of the strongest: Isaiah 53 describes the crucifixion of Jesus in detail — written 700 years before Jesus was born, before crucifixion was even a Roman practice. The Dead Sea Scrolls confirmed those manuscripts predated Christ.\n\n2 Peter 1:20-21 explains how it happened: holy men were \"moved\" by the Holy Ghost — the word means carried along, like a ship carried by wind. The human authors were genuine authors, writing in their own styles and languages. And God superintended every word.",
    memoryHack: "Prophecy fulfilled = the Bible's fingerprint. Isaiah 53 written 700 years early — picture a letter written before the event it describes.",
    challenge: "Read Isaiah 53 today. Then read the crucifixion account in John 19. Write down every detail that matches. Let the evidence speak.",
    prayerStarter: "Lord, strengthen my confidence in Your Word. Where I have doubt, give me evidence. Where I have questions, give me patience.",
  },
  {
    day: 18, phase: 2, phaseName: "The Bible", title: "How to Read Scripture",
    scriptureRef: "2 Timothy 2:15; Joshua 1:8",
    scriptureText: "Study to shew thyself approved unto God, a workman that needeth not to be ashamed, rightly dividing the word of truth.",
    lessonText: "Reading the Bible is a skill — not because God hides Himself, but because language has context, history, and layers. 2 Timothy 2:15 says to \"rightly divide\" the Word of truth. That means there is a wrong way to divide it — pulling verses out of context, applying commands given to specific people in specific situations as universal laws.\n\nThree questions unlock almost any passage: What does it say? What does it mean? What should I do?\n\nJoshua 1:8 gives the method: meditate on it day and night. Meditation in Scripture is not emptying your mind — it is filling it. Turning a verse over and over, seeing it from every angle.",
    memoryHack: "Three reading questions: WHAT does it say? WHAT does it mean? WHAT do I do? Three WHATs. Apply them to every passage.",
    challenge: "Take one verse you already know — John 3:16, for example — and apply the three questions to it fully.",
    prayerStarter: "Lord, teach me to read Your Word with understanding, not just familiarity. Help me to be a student, not just a reader.",
  },
  {
    day: 19, phase: 2, phaseName: "The Bible", title: "The Power of God's Word",
    scriptureRef: "Hebrews 4:12; Isaiah 55:11",
    scriptureText: "For the word of God is quick, and powerful, and sharper than any twoedged sword, piercing even to the dividing asunder of soul and spirit.",
    lessonText: "The word \"quick\" in Hebrews 4:12 means alive. Not once-alive, not symbolically alive — actively, presently alive. The Bible is not a dead record of past events. It is a living instrument in the hands of the Holy Ghost.\n\nA two-edged sword cuts both directions — it does not have a safe side. The Word of God does not leave you where it finds you. It reveals what you're thinking, what you're desiring, what you're hiding. It is a scalpel, not a bludgeon.\n\nIsaiah 55:11 is God's promise about His own Word: it will not return to Him empty. It will accomplish what He sent it to do. When you read Scripture, you are not handling inert text. You are handling something that God has commissioned to do a work in you.",
    memoryHack: "Living, active, sharp — alive, working, cutting. The Word is not furniture in your house; it is a tool in God's hands.",
    challenge: "Read a chapter of Scripture with this question in mind: \"What is God trying to accomplish in me through this passage?\" Write down what you sense.",
    prayerStarter: "God, use Your Word as a scalpel today. Find what needs to change. I am not afraid of what You will show me — I trust Your hands.",
  },
  {
    day: 20, phase: 2, phaseName: "The Bible", title: "Promises You Can Stand On",
    scriptureRef: "Philippians 4:19; Romans 8:28",
    scriptureText: "But my God shall supply all your need according to his riches in glory by Christ Jesus. — And we know that all things work together for good to them that love God.",
    lessonText: "The Bible is full of promises — but not all promises are addressed to everyone. Context matters. Some promises are unconditional; others have conditions embedded in them. Good Bible reading means understanding which is which.\n\nPhilippians 4:19 is unconditional: God will supply every need. Romans 8:28 has a condition: all things work together for good to those who love God and are called according to His purpose.\n\nWhen you find a promise that applies to you — stand on it. Pray it back to God. Remind yourself of it when circumstances contradict it. Promises are not wishful thinking; they are God's word staked against your situation.",
    memoryHack: "Phil. 4:19 = needs met. Romans 8:28 = everything working. Two promises, two cards — write them and put them somewhere visible.",
    challenge: "Find one promise in Scripture that speaks directly to something you're facing right now. Write it on a notecard and carry it with you for the rest of this week.",
    prayerStarter: "Father, You are a promise-keeping God. Help me to find the promises that belong to me, stand on them, and not move off of them when things get hard.",
  },
  {
    day: 21, phase: 2, phaseName: "The Bible", title: "Prayer and the Word Together",
    scriptureRef: "Matthew 6:6; Psalm 5:3",
    scriptureText: "But thou, when thou prayest, enter into thy closet, and when thou hast shut thy door, pray to thy Father which is in secret.",
    lessonText: "Prayer and Scripture are not two separate disciplines — they are two halves of the same conversation. Scripture is God speaking to you. Prayer is you speaking to God. Separated, they are incomplete. Together, they are dialogue.\n\nPsalm 5:3 gives you a rhythm: morning. Before the noise starts. Before the demands arrive. David says \"I will look up\" — not down at problems, not sideways at circumstances, but up. The morning watch is not mandatory law — it is a practical recognition that whoever speaks first in your day tends to win the day.\n\nMatthew 6:6 is not about a literal closet. It is about intentionality — shutting out the distractions long enough to actually be with your Father. Ten minutes of focused conversation beats an hour of distracted wandering.",
    memoryHack: "Scripture = God talking. Prayer = you talking. A conversation requires both. Which side do you spend more time on?",
    challenge: "Before your 10-minute reading today, spend two minutes in silent prayer first. No words, just quiet attention toward God. Then read. Notice the difference.",
    prayerStarter: "Lord, let this time each day be a real conversation — not a duty. Speak to me through Your Word and help me to bring my real self when I pray.",
  },
  {
    day: 22, phase: 2, phaseName: "The Bible", title: "Faith — What It Actually Means",
    scriptureRef: "Hebrews 11:1; Romans 10:17",
    scriptureText: "Now faith is the substance of things hoped for, the evidence of things not seen. — So then faith cometh by hearing, and hearing by the word of God.",
    lessonText: "Faith is not positive thinking. It is not pretending problems don't exist. It is not working yourself into an emotional state.\n\nHebrews 11:1 says faith is the substance of things hoped for. Substance — real, present, tangible in the spirit before it is visible in the physical. Faith does not wait to see before it believes. Faith acts on what God has said and then watches it arrive.\n\nRomans 10:17 tells you where faith comes from: hearing the Word of God. You cannot manufacture faith by trying harder. You grow faith by filling yourself with what God has said. Every time you read Scripture, hear a sermon, or confess a promise, you are cultivating faith.",
    memoryHack: "Hebrews 11:1 in two halves: \"Faith is the substance of things hoped for\" / \"the evidence of things not seen.\" Say the two halves separately, then connect them.",
    challenge: "Read Hebrews 11 — the entire chapter. The \"hall of faith.\" Pick your favorite figure and write one sentence about what their faith looked like in action.",
    prayerStarter: "God, build my faith. I don't want to just know about faith — I want to live in it. Feed my faith through Your Word today.",
  },
  {
    day: 23, phase: 2, phaseName: "The Bible", title: "When Doubt Comes",
    scriptureRef: "John 20:24-29; Jude 1:22",
    scriptureText: "Jesus saith unto him, Thomas, because thou hast seen me, thou hast believed: blessed are they that have not seen, and yet have believed.",
    lessonText: "Thomas doubted. Not as a stranger — as one of the twelve. He had walked with Jesus for three years, witnessed miracles, heard every sermon. And when the resurrection reports came, he said: I won't believe it unless I put my hands in the wounds.\n\nJesus did not dismiss Thomas. He showed up specifically for him. He offered his hands and his side. And Thomas said: \"My Lord and my God.\" Jesus did not scold the doubt — He answered it.\n\nJude 1:22 says to have compassion on some who doubt. That includes yourself. Doubt is not the opposite of faith — it is a question that faith is still big enough to answer. Bring your honest questions to God. He is not frightened by them.",
    memoryHack: "Thomas doubted and Jesus showed up specifically for him. Your honest doubt does not push God away — it can be the thing that draws Him near.",
    challenge: "Write down the hardest question you have about faith, God, or Christianity. Don't bury it. Bring it to God in prayer and then to a pastor or trusted believer.",
    prayerStarter: "Lord, You are not afraid of my questions. I trust You with them.",
  },
  {
    day: 24, phase: 2, phaseName: "The Bible", title: "Old Testament and New — One Story",
    scriptureRef: "Luke 24:27; Matthew 5:17",
    scriptureText: "And beginning at Moses and all the prophets, he expounded unto them in all the scriptures the things concerning himself.",
    lessonText: "On the road to Emmaus, two discouraged disciples walked away from Jerusalem not recognizing the stranger who joined them. He walked them through the entire Old Testament, showing them how it all pointed to the Messiah. Only at the breaking of bread did they recognize Jesus — and they said: \"Did not our heart burn within us?\"\n\nThe Old Testament is not a collection of Jewish history that Christians discard. It is the setup for which Jesus is the resolution. Law, prophecy, Psalms, wisdom literature — every genre points somewhere. Jesus himself said he came not to abolish but to fulfill.\n\nWhen you read the Old Testament, look for Jesus. He is there — in the Passover lamb, in the manna in the wilderness, in the rock that followed Israel.",
    memoryHack: "Old Testament = setup. New Testament = resolution. Same story, one Author. Jesus is the connection point between every part.",
    challenge: "Read Luke 24:13-35 — the Emmaus road story. Put yourself in the disciples' place. What would it have been like to hear Jesus explain all of Scripture as pointing to himself?",
    prayerStarter: "Jesus, walk with me through Your Word the way You walked with those disciples. Let my heart burn while You open the Scriptures to me.",
  },
  {
    day: 25, phase: 2, phaseName: "The Bible", title: "Scripture That Is Hard",
    scriptureRef: "2 Peter 3:15-16; Romans 11:33",
    scriptureText: "O the depth of the riches both of the wisdom and knowledge of God! how unsearchable are his judgments, and his ways past finding out!",
    lessonText: "Peter, writing about Paul's letters, admits that some things in them are \"hard to be understood.\" If the apostle Peter found some of Scripture difficult, you are in good company.\n\nThere are passages that seem to contradict each other until you understand the context. There are commands in the Old Testament that are hard to reconcile with a God of love until you understand the larger narrative arc.\n\nThe honest answer is: some things in Scripture require maturity, study, and humility to navigate. What do you do in the meantime? You start with what is clear. The Gospel is not hidden or obscure. Repentance, faith, baptism, the Holy Ghost — these are stated plainly and repeatedly. Build on what is clear. Let the harder things wait for growth.",
    memoryHack: "Start with what is clear. Don't let what is unclear keep you from obeying what is plain.",
    challenge: "Ask a pastor or Bible teacher about one passage in Scripture that you find confusing or troubling. Let a more experienced voice help you navigate it.",
    prayerStarter: "God, You are deeper than I can fully understand. Give me the humility to sit with mystery without letting it undermine what I know to be true.",
  },
  {
    day: 26, phase: 2, phaseName: "The Bible", title: "Making Bible Reading a Habit",
    scriptureRef: "Psalm 1:1-3; Deuteronomy 11:18-19",
    scriptureText: "But his delight is in the law of the LORD; and in his law doth he meditate day and night.",
    lessonText: "Psalm 1 does not describe a person who reads the Bible out of obligation. It describes a person who delights in it. There is a difference between a duty and a delight — and the goal is to get from one to the other.\n\nDelight comes from encounter. The more you meet God in Scripture, the more you want to come back. But in the early stages, you have to build the habit before the delight is fully formed.\n\nPractical help: same time, same place, every day. Your brain is wired to crave what it consistently does. Ten minutes a day, every day, will change you more in a year than five hours once a week.",
    memoryHack: "Delight comes after habit. Build the habit first. The delight will follow.",
    challenge: "Identify your best 10-minute window each day and protect it this week. If you miss a day, pick it back up the next morning without guilt. The streak matters less than the return.",
    prayerStarter: "Lord, give me a delight in Your Word that goes beyond discipline. Let me come to it hungry, not dutiful.",
  },
  {
    day: 27, phase: 2, phaseName: "The Bible", title: "Memorizing Scripture",
    scriptureRef: "Psalm 119:11; Matthew 4:4",
    scriptureText: "Thy word have I hid in mine heart, that I might not sin against thee.",
    lessonText: "When Satan tempted Jesus in the wilderness, Jesus did not say \"That's not right\" or \"I disagree.\" He said \"It is written\" — and quoted specific Scripture from memory, three times.\n\nThe Word hidden in your heart is available to you in the moment you need it most. On the day when circumstances overwhelm you, you will not have time to look up a verse. What you have memorized is what you will have.\n\nPsalm 119:11 says \"I have hidden Your Word in my heart that I might not sin against you.\" Scripture in your memory functions as a warning system, a correction, a comfort, and a weapon. You cannot hide what you have not learned.",
    memoryHack: "Pick one short verse per week to memorize. Say it when you wake up, say it before lunch, say it before bed. Three times a day — three days — and it is yours.",
    challenge: "Pick one verse from the past two weeks of this journey that meant the most to you. Commit to memorizing it by the end of this week.",
    prayerStarter: "Lord, help me to hide Your Word where no one can take it from me — in my heart. Let it be available in my darkest moment.",
  },
  {
    day: 28, phase: 2, phaseName: "The Bible", title: "The Bible and Your Daily Life",
    scriptureRef: "James 1:22-25; Luke 8:15",
    scriptureText: "But be ye doers of the word, and not hearers only, deceiving your own selves.",
    lessonText: "James gives a blunt warning to people who read the Bible without acting on it: you are deceiving yourself. He compares it to a person who looks in a mirror, walks away, and immediately forgets what they saw. What good did the mirror do?\n\nLuke 8:15 describes the good soil in the parable of the sower as people who hear the Word, keep it, and bear fruit with patience. Three verbs: hear, keep, bear. Keeping is the bridge between hearing and bearing.\n\nToday's reading produces tomorrow's action. The challenge of every daily lesson is not just to understand — it is to identify the one thing you will do differently because of what you read.",
    memoryHack: "Hear > Keep > Bear. Three steps, not one. Reading alone is only the first step.",
    challenge: "Look back at the last five days of readings. Pick one lesson and identify one specific action it should produce in your life this week. Do that action.",
    prayerStarter: "God, make me a doer, not just a hearer. Let Your Word move me — not just inform me.",
  },
  {
    day: 29, phase: 2, phaseName: "The Bible", title: "When You Don't Feel Like Reading",
    scriptureRef: "Matthew 26:41; Galatians 6:9",
    scriptureText: "Watch and pray, that ye enter not into temptation: the spirit indeed is willing, but the flesh is weak. — And let us not be weary in well doing: for in due season we shall reap, if we faint not.",
    lessonText: "There will be days when you sit down to read and feel nothing. The words seem flat. Your mind wanders. You finish the passage and feel like you got nothing out of it.\n\nDo it anyway. Jesus acknowledged in the garden that the flesh is weak — He said it to his disciples, not as a condemnation, but as a fact. Your body and emotions are not always going to cooperate with your spirit's intentions. That is not sin; it is the human condition.\n\nGalatians 6:9 gives the promise attached to perseverance: in due season you shall reap, if you faint not. \"If you faint not\" implies the real possibility of fainting. Some days will be hard. The commitment is to show up anyway — because the reaping is on the other side of the not-fainting.",
    memoryHack: "\"In due season\" means not on your schedule. Plant today. Harvest comes later. Do not judge a day's reading by how it felt.",
    challenge: "The next time you sit down to read and feel nothing, read anyway — then write one sentence about what you read. Showing up is the discipline.",
    prayerStarter: "Lord, I don't always feel like it. But I am here. Use this time even when I can't feel it working.",
  },
  {
    day: 30, phase: 2, phaseName: "The Bible", title: "Phase 2 Review — What the Word Has Done",
    scriptureRef: "Hebrews 11:1",
    scriptureText: "Now faith is the substance of things hoped for, the evidence of things not seen.",
    lessonText: "Two weeks in the Word. Take inventory again.\n\nYou know what the Bible is and why it can be trusted — not just by faith, but by evidence. You have a method for reading it: what does it say, what does it mean, what do I do? You understand the relationship between the Old and New Testaments. You know that doubt is not disqualifying and that perseverance in the habit matters more than any single session.\n\nMost importantly, you have been in the Word for 30 days. That is not nothing. Thirty days of 10-minute seeds in the ground. They are growing whether you can see it or not.\n\nHebrews 11:1 is your verse to carry forward. Faith is not certainty about outcomes — it is confidence in the Person who holds all outcomes.",
    memoryHack: "Hebrews 11:1 — two halves. \"Faith is the substance of things hoped for\" / \"the evidence of things not seen.\" Say both halves from memory right now.",
    challenge: "Read back through your journal or notes from the past two weeks. Write down the three most significant things God has spoken to you through His Word in this phase.",
    prayerStarter: "Father, thank You for thirty days of Your Word working in me. Carry what You have planted in me into the next phase. I am ready to learn how to live it.",
  },
  {
    day: 31, phase: 3, phaseName: "Living It Out", title: "What Is Prayer?",
    scriptureRef: "1 Thessalonians 5:17; Matthew 6:9-13",
    scriptureText: "Pray without ceasing. — After this manner therefore pray ye: Our Father which art in heaven, Hallowed be thy name.",
    lessonText: "Prayer is not a spiritual performance. It is a conversation with your Father — the same Father who already knows what you need before you ask. So why pray? Because prayer is not primarily about giving God information. It is about relationship.\n\n1 Thessalonians 5:17 says \"pray without ceasing\" — which cannot mean stay on your knees 24 hours a day. It means cultivate an orientation of prayer. An ongoing awareness of God's presence.\n\nThe Lord's Prayer is a template, not a script. Jesus gave it as a framework: acknowledge who God is, invite His kingdom, ask for what you need, deal with forgiveness, ask for protection. It covers all of human need in about 60 words.",
    memoryHack: "Prayer = conversation, not performance. You are talking to your Father, not impressing a judge.",
    challenge: "Pray out loud for five minutes today. Not reading a written prayer — talking. It may feel awkward. That is fine. The awkwardness fades with practice.",
    prayerStarter: "Father, teach me to pray the way Your Son prayed — honestly, humbly, and in alignment with Your will.",
  },
  {
    day: 32, phase: 3, phaseName: "Living It Out", title: "Deeper Prayer",
    scriptureRef: "Romans 8:26-27; Jude 1:20",
    scriptureText: "Likewise the Spirit also helpeth our infirmities: for we know not what we should pray for as we ought: but the Spirit itself maketh intercession for us with groanings which cannot be uttered.",
    lessonText: "There are moments when you don't know what to pray. The situation is too complex, the pain too deep, the future too uncertain. You have words, but they feel insufficient for the weight of what you're carrying.\n\nRomans 8:26 is the promise for exactly those moments: the Spirit intercedes for you with groanings that cannot be expressed in words. The Holy Ghost takes what your words cannot carry and carries it for you before God.\n\nJude 1:20 tells believers to build themselves up by praying in the Holy Ghost. This is the tongues prayer — the prayer that bypasses your reasoning mind and comes from the deepest part of your spirit. Paul says in 1 Corinthians 14:4 that the one who prays in tongues \"edifies himself\" — builds himself up.",
    memoryHack: "Praying in the Spirit = construction work on your own soul. Every minute is a brick laid.",
    challenge: "Spend 10 minutes today praying entirely in the Holy Ghost. If you have not yet received the Holy Ghost, spend the time asking God for it with everything you have.",
    prayerStarter: "Holy Spirit, pray through me when I don't know how. Take what I cannot express and carry it before the Father.",
  },
  {
    day: 33, phase: 3, phaseName: "Living It Out", title: "Worship — More Than Music",
    scriptureRef: "John 4:23-24; Psalm 100",
    scriptureText: "But the hour cometh, and now is, when the true worshippers shall worship the Father in spirit and in truth: for the Father seeketh such to worship him.",
    lessonText: "Jesus told the woman at the well that the Father is actively seeking true worshippers. That word \"seeking\" is remarkable — God is not passively waiting to receive worship. He is looking for it. He wants it from you.\n\n\"In spirit and in truth\" — both matter. Worship in spirit without truth becomes emotionalism. Worship in truth without spirit becomes religion: correct but cold, accurate but lifeless.\n\nWorship is not a 30-minute segment of the Sunday service. Worship is a posture — an orientation of your whole self toward God. Romans 12:1 calls it a \"living sacrifice\" — your daily life offered to God as an act of worship.",
    memoryHack: "God is SEEKING worshippers. He is not sitting still — He is looking for people like you who will worship in spirit and truth.",
    challenge: "Put on a worship song today and just listen — no phone, no multitasking. Let the words and music be a vehicle toward God's presence.",
    prayerStarter: "Father, I want to be one of the worshippers You are seeking. Help me to bring my whole self — spirit and truth — to You.",
  },
  {
    day: 34, phase: 3, phaseName: "Living It Out", title: "Corporate Worship",
    scriptureRef: "Psalm 22:3; Hebrews 13:15",
    scriptureText: "But thou art holy, O thou that inhabitest the praises of Israel. — By him therefore let us offer the sacrifice of praise to God continually.",
    lessonText: "God inhabits the praises of His people — not just your personal praise, but the collective voice of a congregation worshipping together. There is something that happens in the gathered worship of a church that cannot happen in your living room alone.\n\nHebrews 13:15 calls it the \"sacrifice of praise.\" Sacrifice because it costs something — it requires you to put aside your circumstances and offer your praise regardless. The word \"continually\" means this is not reserved for good days.\n\nWhen you walk into Elkhart Life Church on Sunday and the congregation lifts their voices together, you are joining something ancient and powerful. You are adding your voice to a sound that reaches heaven. Don't sit it out.",
    memoryHack: "God inhabits the praises — He shows up where the praise is. Your voice matters in the room.",
    challenge: "This Sunday in worship: participate fully. Sing even if you don't feel like it. Let the sacrifice be real.",
    prayerStarter: "God, I bring You praise today — not because I have earned a good day, but because You are worthy regardless of my circumstances.",
  },
  {
    day: 35, phase: 3, phaseName: "Living It Out", title: "Forgiveness — Giving It",
    scriptureRef: "Matthew 6:14-15; Ephesians 4:32",
    scriptureText: "But if ye forgive not men their trespasses, neither will your Father forgive your trespasses. — And be ye kind one to another, tenderhearted, forgiving one another, even as God for Christ's sake hath forgiven you.",
    lessonText: "Jesus makes forgiveness bilateral in Matthew 6: the way you forgive others is directly connected to the forgiveness you receive. Unforgiveness keeps a door closed in your own heart that God is trying to walk through.\n\nForgiveness does not mean what happened was acceptable. It does not require reconciliation in every case. Forgiveness is the release of the debt — \"I am no longer holding this against you before God.\" It frees the forgiver more than the forgiven.\n\nEphesians 4:32 gives the model and the motivation in one sentence: forgive as God for Christ's sake has forgiven you. The standard is what God did for you — completely, at great cost, when you did not deserve it.",
    memoryHack: "Forgiveness = releasing the debt. Not saying it was okay — releasing your right to collect. Picture cutting a rope.",
    challenge: "Is there someone you need to forgive? Write their name. Pray for them — genuinely. Ask God to bless them. This is not weakness; it is spiritual power.",
    prayerStarter: "Lord, I want to forgive the way You have forgiven me. Show me who I am holding something against, and give me the grace to let it go.",
  },
  {
    day: 36, phase: 3, phaseName: "Living It Out", title: "Forgiveness — Receiving It",
    scriptureRef: "1 John 1:9; Psalm 103:12",
    scriptureText: "If we confess our sins, he is faithful and just to forgive us our sins, and to cleanse us from all unrighteousness.",
    lessonText: "Many people find it easier to forgive others than to receive forgiveness for themselves. They confess, receive, then return to carrying the guilt anyway — as if God's forgiveness wasn't quite enough for what they did.\n\n1 John 1:9 is a promise with two parts: God will forgive and He will cleanse. Not just pardon — cleanse. The record is wiped, the residue is removed. And it is based not on the quality of your confession but on His faithfulness.\n\nPsalm 103:12 puts a distance on it: as far as the east is from the west. That is not a finite distance. East and west do not converge — they are infinitely opposed directions. That is how far God removes your sin when you confess it.",
    memoryHack: "East to west — no point of convergence. Infinite distance. Your forgiven sin is that far from you.",
    challenge: "Is there something you have confessed to God but keep picking back up? Pray 1 John 1:9 over it and make a deliberate choice to leave it in God's hands.",
    prayerStarter: "Father, I receive Your forgiveness today — not partially, but fully. Help me to stop carrying what You have already removed.",
  },
  {
    day: 37, phase: 3, phaseName: "Living It Out", title: "Serving Others",
    scriptureRef: "Mark 10:45; Galatians 5:13",
    scriptureText: "For even the Son of man came not to be ministered unto, but to minister, and to give his life a ransom for many. — by love serve one another.",
    lessonText: "The Son of God came to serve. That is not what anyone expected of the Messiah. Instead, Jesus washed feet, touched lepers, ate with outcasts, and said the greatest among you will be your servant.\n\nThis is not a personality type. This is a calling for every follower of Jesus. Galatians 5:13 does not say \"if you are gifted for service, serve.\" It says \"by love serve one another\" — full stop.\n\nService is not a program you sign up for. It is a posture you cultivate. It means walking into a room and asking \"what needs to be done?\" instead of \"what can I get out of this?\" Jesus modeled what it looks like to be the most powerful person in the room and still be the one holding the towel.",
    memoryHack: "Jesus held the towel. The question is not \"what is my role?\" — it is \"what needs doing?\"",
    challenge: "Today, do something for someone with no expectation of thanks, credit, or return. Make it concrete: a specific act for a specific person.",
    prayerStarter: "Jesus, give me Your heart for service. Help me to see needs I normally walk past and to respond the way You would.",
  },
  {
    day: 38, phase: 3, phaseName: "Living It Out", title: "Dealing With Temptation",
    scriptureRef: "1 Corinthians 10:13; James 4:7",
    scriptureText: "There hath no temptation taken you but such as is common to man: but God is faithful, who will not suffer you to be tempted above that ye are able; but will with the temptation also make a way to escape.",
    lessonText: "1 Corinthians 10:13 contains one of the most practical promises in all of Scripture: every temptation has a way of escape. God builds the exit before He allows the entrance. Your job is to look for the exit, not to stand there fascinated with the entrance.\n\nJames 4:7 gives you two actions: \"Submit yourselves therefore to God. Resist the devil, and he will flee from you.\" Both are required. Submit is an active choice to align yourself under God's authority. Resist is confrontation, pushback, refusal.\n\nYou will be tempted. Every Christian is. The goal is not to never be tempted — it is to develop the reflexes to respond correctly when you are.",
    memoryHack: "Every temptation has an exit. Don't look for a way in — look for the way out that God already built.",
    challenge: "Identify your most persistent temptation. Find a specific Scripture to fight it with — one that speaks directly to it. Write it on a card and put it where the temptation typically hits.",
    prayerStarter: "God, You are faithful. When I am tempted today, show me the way of escape. Help me to look for the exit before I need it.",
  },
  {
    day: 39, phase: 3, phaseName: "Living It Out", title: "Generosity and Tithing",
    scriptureRef: "Malachi 3:10; 2 Corinthians 9:7",
    scriptureText: "Bring ye all the tithes into the storehouse... and prove me now herewith, saith the LORD of hosts, if I will not open you the windows of heaven. — God loveth a cheerful giver.",
    lessonText: "Tithing is the first 10% of your income returned to God through the local church. It is the only place in Scripture where God tells you to test Him — \"prove me now herewith.\" He is making a direct challenge and a direct promise: bring the tithe, and watch what happens.\n\n2 Corinthians 9:7 gives the spirit of generosity: give as you have purposed in your heart. Cheerfully, not reluctantly. Freely, not under compulsion.\n\nGenerosity is not fundamentally about money. It is about the condition of your heart toward God and others. A generous person has settled the question of ownership: God owns it all, and I am a steward.",
    memoryHack: "Tithe = first 10%. Not the leftover. The first. It is an act of trust that God will cover the remaining 90%.",
    challenge: "Bring your tithe to church this Sunday — not as a transaction, but as an act of worship. If you have not been tithing, this is the week to start.",
    prayerStarter: "Father, I acknowledge that everything I have comes from You. Help me to hold it loosely and give generously — starting with the tithe.",
  },
  {
    day: 40, phase: 3, phaseName: "Living It Out", title: "Your Mouth — What You Say",
    scriptureRef: "Proverbs 18:21; James 3:9-10",
    scriptureText: "Death and life are in the power of the tongue: and they that love it shall eat the fruit thereof.",
    lessonText: "Proverbs 18:21 is blunt: your tongue carries the power of death and life, and you will eat the fruit of what you speak. What comes out of your mouth is not neutral — it is seed that produces a harvest.\n\nJames 3 is one of the most extended treatments of the tongue in Scripture. He compares it to a ship's rudder — a small thing that determines the direction of the whole vessel. With the same tongue we bless God and curse people. He calls this absurd.\n\nBecoming a Christian does not automatically clean up your speech. That is a discipline. It requires intentionality about what you say, how you say it, and what you say about others when they are not in the room.",
    memoryHack: "Your mouth is a rudder. Small thing, enormous consequences. What direction has your speech been steering your life?",
    challenge: "For the next 24 hours, notice every negative or cutting thing you say. Not to condemn yourself — to see the pattern. Then ask God to help you replace those patterns with something life-giving.",
    prayerStarter: "God, set a guard on my mouth. Let what comes out of me bring life to the people around me, not damage.",
  },
  {
    day: 41, phase: 3, phaseName: "Living It Out", title: "Relationships That Help You Grow",
    scriptureRef: "Proverbs 27:17; 1 Corinthians 15:33",
    scriptureText: "Iron sharpeneth iron; so a man sharpeneth the countenance of his friend. — Be not deceived: evil communications corrupt good manners.",
    lessonText: "Proverbs 27:17 is one of the most honest statements about relationships: iron sharpens iron. That is not a smooth, comfortable process. Sharpening involves friction. The relationships that make you better are not always the most pleasant — they are the ones that tell you the truth.\n\n1 Corinthians 15:33 is equally honest: bad company corrupts good character. You can be sincere about your faith and still be slowly worn down by the people you spend the most time with.\n\nThis is not a call to abandon people who don't know Jesus. It is a call to be intentional about the relationships that shape you — and to make sure some of those relationships are with people who are further down the road than you.",
    memoryHack: "Iron sharpening iron is not a soft process. The friendships that make you better require friction — the honest kind.",
    challenge: "Identify one person in your life who is further along in faith than you. Make a point of spending intentional time with them this week.",
    prayerStarter: "God, send me the relationships I need to grow. Help me to be the kind of friend who makes others better.",
  },
  {
    day: 42, phase: 3, phaseName: "Living It Out", title: "Handling Conflict",
    scriptureRef: "Matthew 18:15; Romans 12:18",
    scriptureText: "Moreover if thy brother shall trespass against thee, go and tell him his fault between thee and him alone. — If it be possible, as much as lieth in you, live peaceably with all men.",
    lessonText: "Jesus did not leave conflict resolution vague. Matthew 18:15-17 gives specific steps: go to the person directly, alone, first. Not to mutual friends. Not to the whole church. Directly, privately, first.\n\nRomans 12:18 adds a qualifier: \"as much as lieth in you\" — meaning you cannot control the outcome, but you can control your part. You can choose not to escalate. You can choose to go first.\n\nConflict handled biblically is one of the clearest proofs of Christian maturity. Anyone can avoid confrontation or weaponize it. It takes genuine character to go directly, humbly, and honestly to the person involved.",
    memoryHack: "Go first. Go directly. Go alone. Three rules for biblical conflict resolution — in that order.",
    challenge: "Is there an unresolved conflict in your life right now? Ask yourself: have I gone directly to this person alone? If not, that is your next step.",
    prayerStarter: "Lord, give me the courage and humility to handle conflict the way You described — not to win, but to restore.",
  },
  {
    day: 43, phase: 3, phaseName: "Living It Out", title: "Rest — The Discipline of Stopping",
    scriptureRef: "Matthew 11:28-30; Mark 6:31",
    scriptureText: "Come unto me, all ye that labour and are heavy laden, and I will give you rest.",
    lessonText: "Jesus invited the heavy-laden to rest. Then he modeled it — stepping away from crowds, withdrawing to pray, telling His disciples \"Come apart and rest a while.\" Rest is not a sign of weakness in the Christian life. It is a discipline, and ignoring it is not holiness.\n\nThe Sabbath principle is built into creation — not as a Jewish ritual to be discarded, but as a pattern woven into the rhythm of human existence. One day in seven for rest, for worship, for reorientation.\n\nYou cannot pour from an empty vessel. The most effective people in the kingdom of God are those who have learned to receive, not just to give. Rest is an act of trust — it says \"God does not need me to hold everything together while I sleep.\"",
    memoryHack: "Rest is not laziness. It is trust. Stopping says: God holds it when I put it down.",
    challenge: "Plan one day this week where you deliberately slow down — no rushing, no work pressure, time for worship and rest.",
    prayerStarter: "Jesus, I come to You heavy laden. I want the rest You promised — the deep settledness that comes from trusting You.",
  },
  {
    day: 44, phase: 3, phaseName: "Living It Out", title: "Walking in Holiness",
    scriptureRef: "1 Peter 1:15-16; Hebrews 12:14",
    scriptureText: "But as he which hath called you is holy, so be ye holy in all manner of conversation; Because it is written, Be ye holy; for I am holy.",
    lessonText: "Holiness is not a set of external restrictions. It is conformity to God's character — being set apart by who you are, not just by what you don't do.\n\n1 Peter 1:15 says to be holy \"in all manner of conversation\" — the word \"conversation\" in KJV means conduct, not just speech. Your entire manner of life. What you do when no one is watching.\n\nHoliness is the natural result of the Holy Ghost working in you from the inside. It is not you gritting your teeth and trying harder. It is you cooperating with the Holy Ghost as He conforms you to the image of Christ. You will know it is working when you notice that things you used to want no longer attract you.",
    memoryHack: "Holiness = being set apart by character, not just rules. The Holy Ghost does the work — you cooperate.",
    challenge: "Ask yourself honestly: is there an area of your life where you are cooperating with the Holy Ghost's work of holiness — and an area where you are resisting it? Name both.",
    prayerStarter: "God, You are holy. Make me more like You — not through willpower, but through genuine transformation from the inside out.",
  },
  {
    day: 45, phase: 3, phaseName: "Living It Out", title: "Phase 3 Review — Living It Out",
    scriptureRef: "Hebrews 10:25",
    scriptureText: "Not forsaking the assembling of ourselves together, as the manner of some is; but exhorting one another: and so much the more, as ye see the day approaching.",
    lessonText: "Two weeks of daily Christianity — not just belief, but practice. Stop and count what you have covered.\n\nYou have a framework for prayer that goes beyond recitation — including praying in the Spirit. You understand worship as a posture, not just a program. You know how to give and receive forgiveness. You have a model for serving, managing temptation, handling your tongue, navigating conflict, and walking in holiness.\n\nHebrews 10:25 is your verse for this phase because it is specifically about showing up — to the community, to the gathering, to one another. \"So much the more as you see the day approaching\" means the closer we get to Christ's return, the more essential the community becomes, not less.",
    memoryHack: "Forsaking = abandoning. Assembling = gathering together. \"Not forsaking the assembling\" = do not abandon your community.",
    challenge: "Call or text someone from your church — not to ask for anything, just to encourage them. Tell them one specific thing you appreciate about them.",
    prayerStarter: "Lord, thank You for thirty days of learning to live what I believe. Let it not be theory — let it be the way I actually move through the world.",
  },
  {
    day: 46, phase: 4, phaseName: "Growing Forward", title: "The Fruit of the Spirit",
    scriptureRef: "Galatians 5:22-25; John 15:5",
    scriptureText: "But the fruit of the Spirit is love, joy, peace, longsuffering, gentleness, goodness, faith, meekness, temperance: against such there is no law.",
    lessonText: "The fruit of the Spirit is not a checklist you work through. It is the organic result of the Holy Ghost working in you over time — the way an apple tree does not strain to produce apples but simply grows them as a natural consequence of being what it is.\n\nNotice it is \"fruit\" (singular) not \"fruits\" (plural). These nine qualities are one integrated reality. You cannot grow love without growing patience. Peace without gentleness is just detachment.\n\nJohn 15:5 gives the condition for fruit: abiding in the vine. \"Apart from me you can do nothing.\" The branch does not produce fruit by trying harder. It produces fruit by staying connected. Your job is the connection — the fruit is the Spirit's job.",
    memoryHack: "Nine qualities, one fruit. An apple tree doesn't try to apple. It grows connected and the fruit comes. Stay connected.",
    challenge: "Pick one fruit from Galatians 5:22 that you most need God to develop in you. Focus on it intentionally this week — pray for it, watch for opportunities to exercise it.",
    prayerStarter: "Holy Spirit, produce in me what I cannot manufacture myself. I want to be a tree that bears fruit — not by effort, but by abiding.",
  },
  {
    day: 47, phase: 4, phaseName: "Growing Forward", title: "Spiritual Gifts",
    scriptureRef: "1 Corinthians 12:7-11; Romans 12:6-8",
    scriptureText: "But the manifestation of the Spirit is given to every man to profit withal.",
    lessonText: "The Holy Ghost does not just change your character — He equips you for ministry. 1 Corinthians 12 lists nine gifts: word of wisdom, word of knowledge, faith, gifts of healing, working of miracles, prophecy, discernment of spirits, tongues, and interpretation of tongues.\n\nRomans 12:6-8 lists motivational gifts: prophecy, service, teaching, exhortation, giving, leadership, mercy. These are built-in capacities that God has wired into you for the benefit of others.\n\nYou have gifts. They may not look dramatic. The person with the gift of mercy who sits with someone in a hospital room for six hours is operating in a supernatural gift — one the church desperately needs. Gifts are not for decoration or status. They are for building the body.",
    memoryHack: "Gifts are given \"to profit withal\" — for everyone's benefit, not your own status. What do you carry that others need?",
    challenge: "Ask two people who know you well: \"What do you think I'm gifted at? Where do you see God using me most naturally?\" Listen carefully.",
    prayerStarter: "Lord, show me what gifts You have placed in me. I want to discover them and use them — for the good of others, not my own advancement.",
  },
  {
    day: 48, phase: 4, phaseName: "Growing Forward", title: "Your Testimony",
    scriptureRef: "Revelation 12:11; 1 Peter 3:15",
    scriptureText: "And they overcame him by the blood of the Lamb, and by the word of their testimony. — be ready always to give an answer to every man that asketh you a reason of the hope that is in you.",
    lessonText: "Your testimony is one of the most powerful weapons in the kingdom of God. Revelation 12:11 links overcoming to testimony — the blood of the Lamb (what Jesus did) combined with the word of their testimony (what it means in your life). One without the other is incomplete.\n\nYour testimony has a simple structure: Before — Encounter — After. What was your life like before you encountered Jesus? What happened when you met Him? What is different now?\n\nYou do not need a dramatic story of rescue from a deep pit. Every testimony is the same story at its core: I was lost, Jesus found me, nothing is the same. Tell that story simply, honestly, and specifically.",
    memoryHack: "Before + Encounter + After = your testimony. Three sentences minimum. Practice until it feels natural to say.",
    challenge: "Write your testimony in 3-5 sentences using the Before-Encounter-After framework. Read it out loud to yourself. Then tell it to one person this week.",
    prayerStarter: "Lord, help me to own my story and tell it well. Let my testimony be a door that others can walk through to find You.",
  },
  {
    day: 49, phase: 4, phaseName: "Growing Forward", title: "Sharing Your Faith",
    scriptureRef: "Matthew 28:19-20; Acts 1:8",
    scriptureText: "Go ye therefore, and teach all nations... — But ye shall receive power, after that the Holy Ghost is come upon you: and ye shall be witnesses unto me.",
    lessonText: "Acts 1:8 says you shall be witnesses. A witness is not an expert — a witness is someone who saw something and reports what they saw. You are not required to have a theology degree, a perfect life, or an answer to every question. You are required to tell what you know.\n\nMatthew 28:19 says \"go\" — and in the original language, it is actually a participle, more accurately translated \"as you are going.\" Wherever you are going — to work, to the grocery store, to your neighbor's house — make disciples. Evangelism is not a special event. It is a way of moving through life.\n\nThe most powerful thing you can say to someone is not a theological argument. It is \"here is what Jesus did in my life.\" Nobody can argue with your story.",
    memoryHack: "Witness = report what you saw. You don't have to be an expert. You just have to be honest.",
    challenge: "Tell one person this week something specific that Jesus has done in your life. Not a presentation, not an argument — just one thing. Then let the conversation go where it goes.",
    prayerStarter: "Lord, make me a witness wherever I go. Give me the courage to speak and the wisdom to know when and how.",
  },
  {
    day: 50, phase: 4, phaseName: "Growing Forward", title: "Fasting",
    scriptureRef: "Matthew 6:16-18; Isaiah 58:6",
    scriptureText: "Is not this the fast that I have chosen? to loose the bands of wickedness, to undo the heavy burdens, and to let the oppressed go free.",
    lessonText: "Fasting is not a hunger strike against God. It is not about earning His attention or impressing Him with your discipline. It is about removing a legitimate need temporarily in order to focus entirely on Him.\n\nJesus said \"when you fast\" — not \"if you fast.\" He assumed His followers would fast. He gave instructions for how to do it without making a public show of it: don't look miserable, don't announce it, let it be between you and God.\n\nIsaiah 58:6 describes what genuine fasting produces: the loosing of bands, the lifting of burdens, freedom for the oppressed. Fasting is not self-punishment — it is a spiritual weapon. It breaks things in the spirit that nothing else seems to reach. Start small: skip one meal. Use that time to pray.",
    memoryHack: "\"When you fast\" — not \"if.\" Jesus assumed you would. Skip a meal. Use the time you would have eaten to pray.",
    challenge: "Fast one meal this week and use that time to pray. Start with whatever God puts on your heart. Stay with it for the full time you would have spent eating.",
    prayerStarter: "Father, I bring You this time — what I would have spent on food, I spend on You. Use this fast to accomplish what only You can do.",
  },
  {
    day: 51, phase: 4, phaseName: "Growing Forward", title: "Spiritual Warfare",
    scriptureRef: "Ephesians 6:10-18; 2 Corinthians 10:4",
    scriptureText: "For the weapons of our warfare are not carnal, but mighty through God to the pulling down of strong holds.",
    lessonText: "You are in a real spiritual conflict. The enemy is not a metaphor — Scripture describes him as a roaring lion who seeks someone to devour, as a deceiver, as a thief who comes to steal, kill, and destroy. Taking him seriously is not paranoia — it is accuracy.\n\nEphesians 6:10-18 gives you the full armor of God: truth (belt), righteousness (breastplate), the Gospel of peace (shoes), faith (shield), salvation (helmet), the Word of God (sword), and prayer. Each piece is specific, purposeful, and necessary.\n\n2 Corinthians 10:4 says the weapons are \"not carnal\" — you do not fight spiritual battles with human strategies or anger. You fight with truth, righteousness, prayer, faith, and the Word. These are not weaker weapons. They are the only weapons that work.",
    memoryHack: "Full armor = Truth + Righteousness + Gospel + Faith + Salvation + Word + Prayer. All seven pieces. None are optional.",
    challenge: "Read Ephesians 6:10-18 slowly. For each piece of armor, write one word describing what you need to do to put it on intentionally today.",
    prayerStarter: "Lord, I put on Your armor today. I am not fighting in my own strength. The battle belongs to You, and I stand in Your authority.",
  },
  {
    day: 52, phase: 4, phaseName: "Growing Forward", title: "When Life Is Hard",
    scriptureRef: "Romans 5:3-5; James 1:2-4",
    scriptureText: "And not only so, but we glory in tribulations also: knowing that tribulation worketh patience; and patience, experience; and experience, hope.",
    lessonText: "James 1:2-4 tells you to \"count it all joy\" when you fall into trials. Not fake positivity. Not pretending it doesn't hurt. The Greek word for \"count\" is a deliberate choice — you decide to count it this way. You choose the interpretation.\n\nRomans 5:3-5 gives you the process: tribulation produces patience. Patience produces experience. Experience produces hope. The order matters. You cannot skip the patience step to get to the hope. The trial IS the pathway.\n\nThis does not mean God causes every bad thing in your life. But it does mean He wastes nothing. The thing that is trying to break you is, in God's hands, becoming the thing that builds you.",
    memoryHack: "Tribulation > Patience > Experience > Hope. Four steps in order. You cannot get hope without going through the others.",
    challenge: "Write about one hard thing in your life, past or present, and ask honestly: what is God building in me through this? What character is this producing?",
    prayerStarter: "God, I trust You with this. What feels like it is breaking me — I believe You are using it. Build in me what can only be built this way.",
  },
  {
    day: 53, phase: 4, phaseName: "Growing Forward", title: "Finding Your Place in the Body",
    scriptureRef: "1 Corinthians 12:12-18; Ephesians 4:11-13",
    scriptureText: "For the body is not one member, but many. — For the perfecting of the saints, for the work of the ministry, for the edifying of the body of Christ.",
    lessonText: "The church is a body — and bodies work because every part functions. An eye that refuses to see is not humility; it is dysfunction. 1 Corinthians 12:18 says God has placed every member in the body \"as it hath pleased him.\" Your assignment in the body of Christ was God's idea.\n\nEphesians 4:11-13 describes the five-fold ministry as existing not so that leaders can do all the ministry, but so that they can equip the saints to do the work of ministry. You are not the audience — you are a participant.\n\nAt Elkhart Life, there are needs that only you can fill — not because you are unique in human ability, but because you are uniquely placed by God in this specific community at this specific moment.",
    memoryHack: "You are not decorative. Every part of the body has a function. Ask: what function am I here to serve?",
    challenge: "Ask a pastor or leader at Elkhart Life: \"Where do you see a need I could help fill?\" Then listen openly — even if the answer surprises you.",
    prayerStarter: "Lord, show me my place in the body. I am not here to watch — I am here to participate. Open the door for me to serve in the way You intend.",
  },
  {
    day: 54, phase: 4, phaseName: "Growing Forward", title: "Discipleship — Making Others",
    scriptureRef: "Matthew 28:19-20; 2 Timothy 2:2",
    scriptureText: "And the things that thou hast heard of me among many witnesses, the same commit thou to faithful men, who shall be able to teach others also.",
    lessonText: "The Great Commission is not just \"go evangelize.\" It is \"make disciples\" — people who are trained and equipped to follow Jesus and then train others. 2 Timothy 2:2 describes four generations in one sentence: Paul > Timothy > faithful men > others. Discipleship multiplies.\n\nYou have been someone's Timothy in this journey. Someone prayed for you, invited you, welcomed you, shared their faith with you. At some point — sooner than you might expect — you will be Paul to someone else.\n\nMaking a disciple is not about having all the answers. It is about walking with someone further behind you on the same road. What have you learned in 54 days? You have enough to help someone who is on day one.",
    memoryHack: "Paul > Timothy > faithful men > others. Four links in a chain. You are not the last link — you are a middle one.",
    challenge: "Think of one person in your life who is further from God than you are right now. Begin to pray for them specifically by name, every day, for the rest of this journey.",
    prayerStarter: "Lord, let what has been invested in me be invested through me. I don't want to receive and stop. Make me a link in the chain.",
  },
  {
    day: 55, phase: 4, phaseName: "Growing Forward", title: "A Life of Prayer",
    scriptureRef: "Daniel 6:10; Luke 18:1",
    scriptureText: "And he kneeled upon his knees three times a day, and prayed, and gave thanks before his God, as he did aforetime. — Men ought always to pray, and not to faint.",
    lessonText: "Daniel had a prayer habit so consistent that his enemies could predict it and use it against him. He prayed three times a day, every day, whether the king allowed it or not. The consistency of the habit is what made him unshakeable when the crisis came.\n\nLuke 18:1 gives you the purpose: men ought always to pray and not faint. Not faint — the alternative to consistent prayer is not neutrality, it is collapse. Prayer is what keeps you upright when the pressure comes.\n\nBy day 55, your daily 10-minute practice has been building something. A habit. A rhythm. A relationship. Do not let it stop at day 60. This is not a 60-day program — it is the beginning of a lifetime of conversation with God.",
    memoryHack: "Daniel's enemies knew his prayer schedule. It was that consistent. What would your enemies know about your prayer life?",
    challenge: "Map out what your prayer life will look like after day 60. Specific time, specific location, specific focus. Write it as a commitment.",
    prayerStarter: "Lord, what started as a discipline is becoming a desire. Don't let me stop at 60 days. Build in me a prayer life that lasts as long as I do.",
  },
  {
    day: 56, phase: 4, phaseName: "Growing Forward", title: "Eternity — Keeping the Long View",
    scriptureRef: "2 Corinthians 4:17-18; Philippians 3:20",
    scriptureText: "For our light and momentary troubles are achieving for us an eternal glory that far outweighs them all. So we fix our eyes not on what is seen, but on what is unseen.",
    lessonText: "The Apostle Paul called his hardships — beatings, shipwrecks, imprisonment, death threats — \"light and momentary troubles.\" Not because they didn't hurt, but because he had learned to view them against the backdrop of eternity.\n\nPhilippians 3:20 grounds this: \"our citizenship is in heaven.\" You are a citizen of another country who happens to be traveling through this one. The way you travel changes dramatically when you remember where home is.\n\nKeeping the long view does not make you passive about the present. It makes you fearless. When you know how the story ends, the middle chapters — however hard — cannot defeat you.",
    memoryHack: "Fix your eyes on what is UNSEEN. That is the eternal. The visible is temporary; the invisible is permanent.",
    challenge: "Write down one current difficulty in your life. Then write what that difficulty looks like from the vantage point of eternity. What will it look like 10,000 years from now?",
    prayerStarter: "God, give me the long view. Help me to not be so gripped by what is temporary that I lose sight of what is eternal.",
  },
  {
    day: 57, phase: 4, phaseName: "Growing Forward", title: "Continuing to Grow",
    scriptureRef: "Philippians 3:13-14; 2 Corinthians 3:18",
    scriptureText: "Brethren, I count not myself to have apprehended: but this one thing I do, forgetting those things which are behind, and reaching forth unto those things which are before.",
    lessonText: "Paul — who had more spiritual experience, more revelation, more suffering for the Gospel than perhaps any person in history — said plainly: I have not arrived. I am still pressing toward the mark.\n\nSanctification is a lifetime process. 2 Corinthians 3:18 says we are being transformed from one degree of glory to the next — present tense, continuous, ongoing. There is no final level in this life. Every level of growth opens into another level of growth.\n\nThis is not discouraging. It is actually liberating. You do not need to be perfect before God can use you. You do not need to have it all figured out before you can serve. You are a work in progress that God is actively working in — and He is patient, thorough, and committed to finishing what He started.",
    memoryHack: "Even Paul said \"I haven't arrived.\" You are not behind. You are in process. Process is where growth happens.",
    challenge: "Write three spiritual goals for the next 60 days — specific, measurable, personal. Share them with someone who will hold you accountable.",
    prayerStarter: "Lord, I am not finished becoming who You intend me to be. Keep working in me. I want more of You — more change, more growth, more of what only You can produce.",
  },
  {
    day: 58, phase: 4, phaseName: "Growing Forward", title: "This Is a Family",
    scriptureRef: "Galatians 6:10; 1 John 4:20-21",
    scriptureText: "As we have therefore opportunity, let us do good unto all men, especially unto them who are of the household of faith.",
    lessonText: "The church is a family — with all the beauty and all the complexity that comes with families. People will disappoint you. Leaders will make mistakes. Someone will say something that lands wrong.\n\nAnd God will also show up in ways that take your breath away. A stranger will say the exact word you needed. Someone you barely know will weep with you over a situation they could not fully understand.\n\n1 John 4:20-21 is direct: you cannot love God and hate your brother. The love of God in you expresses itself toward the people of God around you. You belong to this family. That means you invest in it, protect it, and choose it — not because it is perfect, but because God placed you here.",
    memoryHack: "Household of faith = your family. Families are imperfect and irreplaceable. Show up for yours.",
    challenge: "Do something this week specifically for someone in your church family — not because they asked, not for recognition, just because they are family and family shows up.",
    prayerStarter: "God, thank You for putting me in a family of faith. Help me to love them the way You love them — imperfections and all.",
  },
  {
    day: 59, phase: 4, phaseName: "Growing Forward", title: "He Who Began a Good Work",
    scriptureRef: "Philippians 1:6; Lamentations 3:22-23",
    scriptureText: "Being confident of this very thing, that he which hath begun a good work in you will perform it until the day of Jesus Christ. — It is of the LORD's mercies that we are not consumed, because his compassions fail not. They are new every morning.",
    lessonText: "You are one day away from completing 60 days. Look back at where you started.\n\nPhilippians 1:6 is one of the most encouraging promises in Scripture: God will finish what He started in you. Not \"God might.\" Not \"God will try.\" He will perform it. He is committed to your completion.\n\nLamentations 3:22-23 — written by a man watching his city destroyed and his people in exile — declares: God's mercies are new every morning. Not recycled. Not diminishing. New. Whatever yesterday looked like, today is a fresh supply of mercy.\n\nYou have built something in 60 days. Habits you did not have before. Scripture in your memory. A community. A relationship with a God who is not finished with you.",
    memoryHack: "He who BEGAN will PERFORM it. The same God who started this in you is the One who will complete it. You are not on your own.",
    challenge: "Write a letter to yourself about what God has done in these 60 days. Specific things. Real changes. Seal it and open it in six months.",
    prayerStarter: "Father, thank You that You started this in me and You intend to finish it. I trust Your timeline. I trust Your process. I trust You.",
  },
  {
    day: 60, phase: 4, phaseName: "Growing Forward", title: "Day 60 — Celebrate, Recommit, Keep Going",
    scriptureRef: "Philippians 1:6; Joshua 1:9",
    scriptureText: "Have not I commanded thee? Be strong and of a good courage; be not afraid, neither be thou dismayed: for the LORD thy God is with thee whithersoever thou goest.",
    lessonText: "You made it. Sixty days. Six hundred minutes of intentional time with God. Sixty Scripture readings. Sixty challenges. Whatever you completed, whatever you missed and restarted, you are here.\n\nNow — don't stop.\n\nThe goal was never to complete a program. The goal was to establish a life. Everything you have built in 60 days — the habit of reading, the posture of prayer, the rhythm of church, the practice of service — is designed to become permanent, not to be a memory.\n\nJoshua 1:9 is God's charge to a new leader stepping into new territory: be strong and courageous. Do not be afraid. Do not be dismayed. Because — the whole thing rests on this — the LORD your God is with you wherever you go. That is still true. It will always be true. Keep going.",
    memoryHack: "Joshua 1:9 — Strong. Courageous. Not afraid. Not dismayed. With God wherever you go. Five phrases, one lifetime.",
    challenge: "Three things today: (1) Mark this day — do something to acknowledge what happened in these 60 days. (2) Tell someone what God has done. (3) Ask your pastor what comes next, and start it.",
    prayerStarter: "God — thank You. For every day. For every moment You showed up. For what You started and what You are still building. I am Yours. Lead me forward. I will follow.",
  },
];

export function getLessonMeta(lesson: Lesson) {
  return {
    day: lesson.day,
    phase: lesson.phase,
    phaseName: lesson.phaseName,
    title: lesson.title,
    scriptureRef: lesson.scriptureRef,
  };
}
